language: python
env:
- TOXENV=py27-django111
- TOXENV=py34-django111
- TOXENV=py34-django20
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django-111
    - python: 3.5
      env: TOXENV=py35-django-20
    - python: 3.5
      env: TOXENV=py35-django-master
    - python: 3.6
      env: TOXENV=py36-django-111
    - python: 3.6
      env: TOXENV=py36-django-20
    - python: 3.6
      env: TOXENV=py36-django-master
  allow_failures:
    - env: TOXENV=py35-django-master
    - env: TOXENV=py36-django-master
install:
- pip install tox
script:
- tox
